#!/usr/bin/env bash
set -euo pipefail

V3_ROOT=/home/liuzhirui/Project/physGen/code/v3
DEMO_TAG=${DEMO_TAG:-$(date -u +%Y%m%d-%H%M%S)}

export CFG_MODE=separate
export GUIDE_SCALE=${GUIDE_SCALE:-5.0}
export PHYS_GUIDANCE_SCALE=${PHYS_GUIDANCE_SCALE:-2.0}
export CONDITIONING_VARIANT=strong_stage_json
export STAGE_STRENGTH=${STAGE_STRENGTH:-0.0}
export STAGE_RATIO_TO_GLOBAL=${STAGE_RATIO_TO_GLOBAL:-0.05}
export JSON_GLOBAL_RATIO_TO_GLOBAL=${JSON_GLOBAL_RATIO_TO_GLOBAL:-0.01}
export JSON_STAGE_RATIO_TO_GLOBAL=${JSON_STAGE_RATIO_TO_GLOBAL:-0.02}
export CONDITION_EXTRA_CAP_RATIO=${CONDITION_EXTRA_CAP_RATIO:-0.10}
export CONDITION_NORM_MAX_SCALE=${CONDITION_NORM_MAX_SCALE:-10.0}
export STAGE_BLOCK_START=${STAGE_BLOCK_START:-14}
export STAGE_BLOCK_STOP=${STAGE_BLOCK_STOP:-24}
export CONDITIONING_AUDIT=${CONDITIONING_AUDIT:-1}
export RUN_ID=${RUN_ID:-trace-v3-m3-v2-json-${DEMO_TAG}}

exec "${V3_ROOT}/inference/infer_trace_writer_m3.sh"
